logging.level.com.reliaquest: DEBUG
spring.application.name: employee-api
server.port: 8111
server.mock.employee.url : http://localhost:8112/api/v1/employee
spring.cache.type : caffeine
spring.cache.caffeine.spec : maximumSize=100,expireAfterWrite=10m
